### ISSUE TITLE
error when select ultisnip element in completion list with tsserver

### ISSUE THREAD

**Issue by greeschenko** [yegappan/lsp#215]
How I understand tsserver tries to handle completion elements and find documentation, description or simply this element in the server completion list.

How can I prevent this check for added completion elements from Ultisnips?

With gopls server, I don't see this problem.

```

Error(LSP): request completionItem/resolve failed (Request completionItem/resolve failed with message: Error processing request. Cannot read properties of unde
fined (reading 'indexOf')^@TypeError: Cannot read properties of undefined (reading 'indexOf')^@    at normalizeSlashes (/usr/lib64/node_modules/typescript/lib/
tsserver.js:6014:26)^@    at Object.normalizePath (/usr/lib64/node_modules/typescript/lib/tsserver.js:6128:16)^@    at Object.toNormalizedPath (/usr/lib64/node
_modules/typescript/lib/tsserver.js:159741:23)^@    at Session.getFileAndProjectWorker (/usr/lib64/node_modules/typescript/lib/tsserver.js:168067:35)^@    at S
ession.getFileAndProject (/usr/lib64/node_modules/typescript/lib/tsserver.js:168051:29)^@    at Session.getCompletionEntryDetails (/usr/lib64/node_modules/type
script/lib/tsserver.js:168255:31)^@    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/lib64/node_modules/typescript/lib/tsserver.js:167087:61)^@
   at /usr/lib64/node_modules/typescript/lib/tsserver.js:168880:88^@    at Session.executeWithRequestId (/usr/lib64/node_modules/typescript/lib/tsserver.js:168
871:28)^@    at Session.executeCommand (/usr/lib64/node_modules/typescript/lib/tsserver.js:168880:33)^@    at Session.onMessage (/usr/lib64/node_modules/typesc
ript/lib/tsserver.js:168906:35)^@    at Interface.<anonymous> (/usr/lib64/node_modules/typescript/lib/tsserver.js:171511:31)^@    at Interface.emit (node:event
s:513:28)^@    at [_onLine] [as _onLine] (node:internal/readline/interface:422:12)^@    at [_normalWrite] [as _normalWrite] (node:internal/readline/interface:6
15:22)^@    at Socket.ondata (node:internal/readline/interface:249:23)^@    at Socket.emit (node:events:513:28)^@    at addChunk (node:internal/streams/readabl
e:324:12)^@    at readableAddChunk (node:internal/streams/readable:297:9)^@    at Readable.push (node:internal/streams/readable:234:10)^@    at Pipe.onStreamRe
ad (node:internal/stream_base_commons:190:23), code = -32603)
   
```

**Comment by greeschenko** [comment]
fix in https://github.com/yegappan/lsp/pull/230
